version: '3'
services:
  mchprs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 25562:25565
    volumes:
      - /srv/mchprs/data:/data
      - /srv/redstonefun_server/plugins/WorldEdit/schematics:/data/schems/rf
      - /srv/mchprs/target
